### ISSUE TITLE
minkorrekt organisation

### ISSUE THREAD

**Issue by worldpotato** [tmechen/minkorrekt_chinagadgets#10]
Hi, wir haben eine minkorrekt organisation gegründet und würden gerne die einzelnen projekte unter dieser zusammen führen um sie gemeinsam zu pflegen.

 Würde uns freuen, wenn die minkorrekt_chinagadgets ein Teil davon werden.

Orga: https://github.com/Minkorrekt-Fakts

**Comment by tmechen** [comment]
gerne :)
transfer project oder lieber forken? 
beim fork könnten wir den link live halten bis er auf der minkorrekt homepage geändert wurde

**Comment by tmechen** [comment]
projekt wurde übertragen, info an minkorrekt für linkfix ist raus.
