### ISSUE TITLE
tinydeal-Link nicht mehr verfügbar

### ISSUE THREAD

**Issue by JayEn84** [tmechen/minkorrekt_chinagadgets#9]
Leider gibt es tinydeal nicht mehr, sodass der Link vom 26.10.2016 nicht mehr funktioniert.

**Comment by tmechen** [comment]
Hast du die Folge grad gehört und kannst mit der Beschreibung das Produkt woanders finden? Ansonsten würde ich heute Abend mal drüberhören und schauen ob ich einen Alternativlink erzeugen kann

**Comment by JayEn84** [comment]
Leider nein, ich habe den Podcast erst kürzlich entdeckt und bin ca. bei Folge 70.

Ich kann die Webseite über archive.org aber noch finden - wenn auch auf Russisch:
https://web.archive.org/web/20190502122122/http://www.tinydeal.com/anti-sleep-alarm-drive-alert-driver-awake-driver-alarm-truck-tool-p-159085.html

Woanders finde ich das Produkt leider nicht.

**Comment by tmechen** [comment]
https://www.amazon.de/dp/B07GGW3LS1 

scheint (mehr oder weniger) das zu sein oder?

**Comment by JayEn84** [comment]
Du hast Recht, ich hatte wohl schlecht gesucht. :)

**Comment by tmechen** [comment]
Herzlichen Dank für den Hinweis, habs grad gefixt und auf amazon gelinkt :)
